name = "cf-ai-chat"
main = "src/worker.js"
compatibility_date = "2026-01-07"

[ai]
binding = "AI"

kv_namespaces = [
  { binding = "CHAT_HISTORY", id = "a6d5e4f7564d4d6aa21aa4832ecb4449", preview_id = "a6d5e4f7564d4d6aa21aa4832ecb4449" }
]

# 建议删除下面这行，用 wrangler secret put CHAT_PASSWORD 代替
# [vars]
# CHAT_PASSWORD = "123"
